### PR TITLE
UI: Changed the padding of y-axis in the privacy policy page to decrease … #144

### LINKED ISSUE #144: UI: Too much negative/blank space in the privacy route
On the Y-axis on the privacy route, blank space is too much which makes the page unnecessarily scrollable.

Screenshots:
Screenshot (23)
 
Screenshot (24)

EXPECTED UI:
The padding from the top and bottom should be reduced.

### PR DESCRIPTION
**Pull request by poswalsameer**
PR Description:
This PR solves the issue of unnecessary blank space or extra padding on the Y-axis in the privacy policy route. Gave different padding values to different screens to ensure responsiveness across multiple devices.

Fixes #144

### CODE REVIEW

**Comment by poswalsameer** [comment]
Hi,
If anyone is seeing this PR, I have solved the padding issue that I created earlier. Kindly review this PR so it can be merged into production.

**Comment by vatan45** [comment]
Hey @poswalsameer   rakshit will soon be sharing a project timeline with all, he is  building v2 rn once thats done it's ready to take  forward

> Hi, If anyone is seeing this PR, I have solved the padding issue that I created earlier. Kindly review this PR so it can be merged into production.

Hey @poswalsameer  rakshit will soon be sharing a project timeline with all, he is  building v2 rn once thats done it's ready to take  forward, after that contributions are most welcomed

**Comment by poswalsameer** [comment]
> Hey @poswalsameer rakshit will soon be sharing a project timeline with all, he is building v2 rn once thats done it's ready to take forward
> 
> > Hi, If anyone is seeing this PR, I have solved the padding issue that I created earlier. Kindly review this PR so it can be merged into production.
> 
> Hey @poswalsameer rakshit will soon be sharing a project timeline with all, he is building v2 rn once thats done it's ready to take forward, after that contributions are most welcomed

Alright, I will be waiting for the v2 to go on prod, so we can start contributing to it.

**Comment by poswalsameer** [comment]
> Hi guys @vatan45 @poswalsameer , i'll merge this for now. Getting v2 done ASAP.

Hi, thanks for merging. Waiting for the v2 to contribute to it more.

**Comment by poswalsameer** [comment]
> yes just caught up with work, we've got the oauth credentials from chesscom so a whole new auth flow will be dropping soon

sounds cool!

**Pull request merged**
