### PR TITLE
UI fix: overflow

### PR DESCRIPTION
**Pull request by Sahillrathore**
Fixed the UI of signupcallback page that were overflowing on all device width.

### CODE REVIEW

**Comment by Sahillrathore** [comment]
> Hey Can you add before after screenshots?

Of the UI issue?

**Comment by Sahillrathore** [comment]
> Yes of the UI issue , and after fixing

IMG_20240716_230138

**Comment by Dinesh-Gautam** [comment]
This is already fixed in #10 
image

**Comment by manjotsk** [comment]
@Bot-Rakshit Seems like there is only one file change in this PR? i can only see one change.

**Pull request closed without merging**
