### PR TITLE
fix : make common header component for all pages

### PR DESCRIPTION
**Pull request by ARSHIL1804**
fixes: #73

### CODE REVIEW

**Comment by Prathamesh-B** [comment]
Can you attach screenshots

**Comment by ARSHIL1804** [comment]
image
image
image

**Review by Prathamesh-B — CHANGES_REQUESTED** [review]
Make them responsive for mobile

**Comment by ARSHIL1804** [comment]
image
Made it responsive
but we can change this whole sidebar with hamburger in future.

**Pull request closed without merging**
